include(joinpath(@__DIR__, "troposphere.jl"))
include(joinpath(@__DIR__, "ionosphere.jl"))
include(joinpath(@__DIR__, "beam.jl"))
include(joinpath(@__DIR__, "instrumentpol.jl"))
include(joinpath(@__DIR__, "stationgains.jl"))
include(joinpath(@__DIR__, "bandpass.jl"))
include(joinpath(@__DIR__, "noise.jl"))
